# Set up device controls, including top button display dimming control
number:
  - platform: template
    name: "Temperature Offset ${deg_c_str}"
    id: temp_offset
    icon: "mdi:thermometer-alert"
    min_value: -10.0
    max_value: 10.0
    step: 0.1
    restore_value: true
    initial_value: 0.0
    entity_category: "CONFIG"
    optimistic: true
  - platform: template
    name: "Humidity Offset %"
    id: hum_offset
    icon: "mdi:water-percent-alert"
    min_value: -10.0
    max_value: 10.0
    step: 0.1
    restore_value: true
    initial_value: 0.0
    entity_category: "CONFIG"
    optimistic: true
  - platform: template
    id: backlight_brightness
    name: "Backlight Brightness"
    icon: "mdi:lightbulb"
    min_value: 0
    max_value: 100
    restore_value: true
    initial_value: 33
    step: 1
    optimistic: true
    on_value:
      - lambda: |-
          if(x > 0) { id(back_light).turn_on().set_brightness(x/100).perform(); }
          else if(x == 0) { id(back_light).turn_off().perform(); }

select:
  - platform: template
    name: "Device Temperature Display Units"
    id: temp_unit_control
    icon: "mdi:thermometer-alert"
    optimistic: true
    entity_category: "CONFIG"
    options:
      - "${deg_c_str}"
      - "${deg_f_str}"
    restore_value: true

output:
  - platform: ledc
    pin: GPIO15
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    internal: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    id: top_btn
    filters:
      - delayed_on: 10ms
      - delayed_off: 500ms
    on_press:
      then:
        - lambda: |-
            // Each press increases brightness 20%, up to 100%.  At 100% press sets brightness to 0%.
            int brightness = id(backlight_brightness).state;
            if (isnan(brightness)) { brightness = 20; }
            else if (brightness == 100) { brightness = 0; }
            else { brightness += 20; }
            if ( brightness > 100) { brightness = 100; }
            id(backlight_brightness).make_call().set_value(brightness).perform();
