# Set up display dimming from top button
output:
  - platform: ledc
    pin: GPIO15
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    internal: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    id: top_btn
    filters:
      - delayed_on: 10ms
      - delayed_off: 500ms
    on_press:
      then:
        - lambda: |-
            switch(id(dbright)){
              case 0: id(dbright) = 4; id(backlight_brightness_control).make_call().set_value(100).perform(); return;
              case 1: id(dbright) = 0; id(backlight_brightness_control).make_call().set_value(0).perform(); return;
              case 2: id(dbright) = 1; id(backlight_brightness_control).make_call().set_value(5).perform(); return;
              case 3: id(dbright) = 2; id(backlight_brightness_control).make_call().set_value(10).perform(); return;
              case 4: id(dbright) = 3; id(backlight_brightness_control).make_call().set_value(33).perform(); return;
            }

# Finished with display dimming
